### ISSUE TITLE
VSS vector search extension and bundling option 

### ISSUE THREAD

**Issue by Volland** [OP-Engineering/op-sqlite#86] opened 2024-04-22 17:25 UTC
I really love the bundling idea .
VSS https://github.com/asg017/sqlite-vss couild be also a good idea for ai powered app vector search is a critical feature

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/OP-Engineering) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/OP-Engineering/op-sqlite/issues/86">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/86/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/OP-Engineering/op-sqlite/issues/86/pledge.svg">
</picture>
</a>

**Comment by ospfranco** [comment] 2024-04-22 18:08
💰 requested or PRs are welcome

**Comment by ospfranco** [comment] 2024-04-23 05:39
Duplicate of #79

**Closed by ospfranco** 2024-04-23 05:39 UTC
Labels: Fund
