### ISSUE TITLE
Prepared statement sometimes reuse previous queries / bind sometimes doesn't work properly

### ISSUE THREAD

**Issue by SrMouraSilva** [OP-Engineering/op-sqlite#37] opened 2024-01-18 00:11 UTC
First, of all, thank you for this awesome library!

**Describe the bug**
Sometimes, prepared statement reuse previous queries without replace parameters sent by bind, so the same query is runned.

**Versions:**
 - OS and version: Android 12
 - op-sqlite version: 2.0.13
 - RN version: 0.73.2

**Reproducible example**

```ts
// Open database
const database = open({
  name: `../files/${databaseName}`,
});

// Create statement
const statement = database.prepareStatement(`
    select id_musica, titulo, letra, compositores, midias
      from musica
    where id_musica = ?
`);

// Bind and execute
statement.bind([123]);
console.log(statement.execute());

// Wait a random time, like close a screen and open again
// Bind and execute
statement.bind([321]);
console.log(statement.execute());

// do some iterations, sometimes the error doesn't occurs at first time
// but I don't noticed any pattern :/
```

I noticed that bind and execute both don't requires await. Is it expected?

**Comment by ospfranco** [comment] 2024-01-18 07:31
thanks for reporting. let me take a look there might be something wrong.

**Comment by ospfranco** [comment] 2024-01-18 08:48
took another look at the code but everything looks correct. I also added another test to the example app and everything seems to be working (failing test highlighted, made it fail just for clarity). Maybe you can create a reproduction repo.

![Oscar Franco Screen 000840](https://github.com/OP-Engineering/op-sqlite/assets/1634213/2b809d7e-28c5-4a64-9763-ea0c5e07d5e7)

**Comment by SrMouraSilva** [comment] 2024-01-18 14:18
Thanks @opsfranco. I will prepare a reproduction repo

**Comment by ospfranco** [comment] 2024-01-21 19:15
Going to close this for now, as I cannot find anything wrong. Feel free to post a reproduction demo and I will re-open it.

**Closed by ospfranco** 2024-01-21 19:15 UTC

**Comment by puelocesar** [comment] 2024-10-21 08:45
I'm trying to benchmark using prepared statements vs not using it, but when I use them, I always get the same results as the first bind. Am I using it wrong or could it be a bug in the library?

Here's my code:

```
let totalTime = 0;
  for (let i = 0; i < 10; i++) {
    const time = performance.now();

    const { rows } = await db.execute(
      'SELECT * FROM nav WHERE lat BETWEEN ? AND ? AND lng BETWEEN ? AND ?;',
      [
        TEST_REGION.bottomLeft[1] + i / 10, // Latitude (38)
        TEST_REGION.topRight[1] + i / 10, // Latitude (40)
        TEST_REGION.bottomLeft[0] + i / 10, // Longitude (-77)
        TEST_REGION.topRight[0] + i / 10, // Longitude (-75)
      ]
    );

    const length = rows.length;
    const duration = performance.now() - time;

    log('sqlite', length, 'results, ', duration, 'ms');
    totalTime += duration;
  }
```

Prints:
```
LOG  sqlite 1255 results,  1738.4134600013494 ms
 LOG  sqlite 1071 results,  32.31616699695587 ms
 LOG  sqlite 963 results,  8.09366700053215 ms
 LOG  sqlite 472 results,  8.815166994929314 ms
 LOG  sqlite 297 results,  2.806416004896164 ms
 LOG  sqlite 350 results,  3.0414169877767563 ms
 LOG  sqlite 197 results,  5.512125000357628 ms
 LOG  sqlite 152 results,  17.757624998688698 ms
 LOG  sqlite 118 results,  2.0722499936819077 ms
 LOG  sqlite 67 results,  1.826875001192093 ms
 LOG  sqlite total time: 1820.65516898036 ms avg: 182.065516898036 ms
 ```

Now with prepared statements:

```
const statement = db.prepareStatement(
    'SELECT * FROM NavAid WHERE lat BETWEEN ? AND ? AND lng BETWEEN ? AND ?;'
  );

  let totalTime = 0;
  for (let i = 0; i < 10; i++) {
    const time = performance.now();

    statement.bind([
      TEST_REGION.bottomLeft[1] + i / 10, // Latitude (38)
      TEST_REGION.topRight[1] + i / 10, // Latitude (40)
      TEST_REGION.bottomLeft[0] + i / 10, // Longitude (-77)
      TEST_REGION.topRight[0] + i / 10, // Longitude (-75)
    ]);

    const { rows } = await statement.execute();

    const length = rows.length;
    const duration = performance.now() - time;

    log('op sqlite', length, 'results, ', duration, 'ms');
    totalTime += duration;
  }
```

It prints: 
```
 LOG  sqlite 1255 results,  5.776457995176315 ms
 LOG  sqlite 1255 results,  4.657541006803513 ms
 LOG  sqlite 1255 results,  4.67383399605751 ms
 LOG  sqlite 1255 results,  4.591749995946884 ms
 LOG  sqlite 1255 results,  4.030249997973442 ms
 LOG  sqlite 1255 results,  4.433375000953674 ms
 LOG  sqlite 1255 results,  4.580458000302315 ms
 LOG  sqlite 1255 results,  5.831000000238419 ms
 LOG  sqlite 1255 results,  6.412834003567696 ms
 LOG  sqlite 1255 results,  7.349167004227638 ms
 LOG  sqlite total time: 52.336667001247406 ms avg: 5.233666700124741 ms
```

Unfortunately, I'm following just as I read in the documentation, so I cannot figure out what's wrong with my bind statement

**Comment by ospfranco** [comment] 2024-10-21 10:15
I think you got the concept of prepared statements wrong. Binding will plan the query on the DB which is the expensive part of the operation. By calling bind inside of the loop you don't get any performance benefit. Your timings seem to have a lot of variation as well, are you using react-native-performance? which has a monotonic clock.

**Comment by puelocesar** [comment] 2024-10-22 10:48
Ok, I got it wrong then. I thought the point was to prepare once and bind it multiple times with different values. Because the documentation led me to think we could do this:

```
const statement = db.prepareStatement('SELECT * FROM User WHERE name = ?;');

// bind the variables in the order they appear
statement.bind(['Oscar']);
let results1 = await statement.execute(); // <- would get Oscar user

statement.bind(['Carlos']);
let results2 = await statement.execute(); // <- would get Carlos user
```

And that's what I'm trying to achieve, to prepare only once, and then bind it to different values

**Comment by puelocesar** [comment] 2024-10-22 11:06
Let's consider this use case, I search for points in a region a lot of times, so I thought I could prepare the statement to optimize it.

My initial code was something like this:
```
useEffect(() => {
    db.execute(
      `SELECT * FROM points WHERE lat BETWEEN ? AND ? AND lng BETWEEN ? AND ?;`,
      queryParams
    ).then(({ rows }) => {
      console.log(rows.map((r) => r._id));
    });
  }, [db, queryParams]);
  ```
  
 I then tried to optimize it by doing:
 ```
const preparedQuery = useMemo(
    () =>
      db.prepareStatement(
        `SELECT * FROM points WHERE lat BETWEEN ? AND ? AND lng BETWEEN ? AND ?;`
      ),
    [db]
  );

  useEffect(() => {
    preparedQuery.bind(queryParams);
    preparedQuery.execute().then(({ rows }) => {
      console.log(rows.map((r) => r._id));
    });
  }, [db, navAidsFilter, preparedQuery, queryParams]);
```

But in the second version, it will always return the values from the first time I called bind, and never change.

**Comment by ospfranco** [comment] 2024-10-22 11:17
No, binding is what actually executes the preparation of the query statement with the database. calling `prepareStatement` just creates the object internally. For your use case using prepared statements will bring no benefits.
